FROM alpine

# 既存ディレクトリ
ADD lipsum.txt /tmp
ADD lipsum.txt /tmp/lipsum2.txt

ADD lipsum.tar.gz /tmp

ADD https://raw.githubusercontent.com/YA-androidapp/Docker-Cheatsheet/main/LICENSE /tmp

# 新規ディレクトリ
ADD lipsum.txt /lipsum1
ADD lipsum.tar.gz /lipsum2
ADD https://raw.githubusercontent.com/YA-androidapp/Docker-Cheatsheet/main/LICENSE /lipsum3

ADD lipsum.txt /lipsum4/
ADD lipsum.tar.gz /lipsum5/
ADD https://raw.githubusercontent.com/YA-androidapp/Docker-Cheatsheet/main/LICENSE /lipsum6/
